name: dbm
channels:
  - pytorch
  - nvidia
dependencies:
  - boto3
  - conda-forge::awscli
  - conda-forge::addict
  - conda-forge::black-jupyter=23.12.1
  - conda-forge::geopy
  - conda-forge::imageio
  - conda-forge::ipdb
  - conda-forge::nbdime
  - conda-forge::pyquaternion
  - conda-lock
  - coverage
  - isort=5.13.2
  - jupyter
  - matplotlib
  - more-itertools
  - numpy=2.0.2
  - pandas
  - Pillow
  - pip
  - pre-commit
  - python=3.11
  - scikit-learn
  - scipy
  - simplejson
  - tqdm
  - invoke
  - pip:
      - setuptools
      - -e . --config-settings editable_mode=compat  # editable_mode=compat insure adding the package to sys.path
      - opencv-python-headless
      - nvidia-ml-py3
      - mcap-ros2-support
      - datetimerange
      - typeguard
      - librosa
      - openai-whisper
      - nbformat
      - pydub
      - noisereduce
      - whisper
      - stable-ts
      - datetimerange
      - PyYAML
      - jsonargparse
      - black
      - plotly
      - ipywidgets
      - metaphone
      - python-Levenshtein
      - moviepy
      - git+https://github.com/DiGyt/cateyes.git
      - ffmpeg
      - tsfresh
      - wandb
      - pyarrow
      - positional-encodings[pytorch]
      - einops
